refactor: improve type safety of errors
safe-global/safe-wallet-web pull request #2039
Opened 2023-05-25 05:56 UTC by iamacook

## What it solves

Removes needs to cast `Error`s

## How this PR fixes it

Caught errors are typed as `unknown` because they can have any value. As such, we were blindly casting them to `Error`.

A new `asError` function is now used to coerce the `unknown` errors into an `Error` instance accordingly.

## How to test it

Observe all unit tests passing.

## Checklist
* [ ] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [x] I've written a unit/e2e test for it (if applicable) 🧑‍💻

2023-05-25 07:08 UTC, katspaugh requested changes
Although neat, I'm apprehensive of adding an import every time I need to handle an error just to cast it. We already import `logError` in most of those cases, so maybe we could modify `logError` so that it accepts the entire error object (whatever that might be) and uses `asError` internally.

2023-05-25 07:41 UTC, iamacook commented
> We already import `logError` in most of those cases, so maybe we could modify `logError` so that it accepts the entire error object (whatever that might be) and uses `asError` internally.

I've refactored this accordingly, leaving a few as is when the error is needed beyond `logError`.

2023-05-25 12:50 UTC, katspaugh reviewed
There's a few places where you're still passing a message to logError instead of the thrown object.

2023-05-25 12:50 UTC, katspaugh commented on src/components/tx/modals/BatchExecuteModal/ReviewBatchExecute.tsx
> +      logError(Errors._804, err.message)
Should it be `logError(Errors._804, err)`?

2023-05-25 13:48 UTC, katspaugh approved these changes
Thanks! 👍

2023-06-19 16:32 UTC, iamacook commented
Closing in favour of https://github.com/safe-global/safe-wallet-web/pull/2127.

2023-06-19 16:32 UTC, closed without merging