fix: Adjust overview widget on dashboard for new design
safe-global/safe-wallet-web pull request #2782
Opened 2023-11-09 12:57 UTC by usame-algan

## What it solves

Updates the dashboard overview widget to support easy on-ramping

Figma: https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=8786%3A68251&mode=dev

## How this PR fixes it

## How to test it

1. Open a Safe
2. Go to the dashboard
3. Observe the updated design
4. Switch to a network where the Ramp Network app is activated
5. Observe a "Buy crypto" button

## Screenshots
<img width="649" alt="Screenshot 2023-11-09 at 13 57 10" src="https://github.com/safe-global/safe-wallet-web/assets/5880855/d1d7f81f-be9c-4f2d-ab37-3d72c5ab6578">
<img width="624" alt="Screenshot 2023-11-09 at 13 57 27" src="https://github.com/safe-global/safe-wallet-web/assets/5880855/269fbe23-38d2-4720-96eb-180a9d4edff3">

## Checklist
* [ ] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

2023-11-09 13:44 UTC, schmanu approved these changes
LGTM!

2023-11-09 13:47 UTC, schmanu requested changes
I just realized that in Dark mode the icons do not adjust their color.

2023-11-09 13:47 UTC, schmanu commented on public/images/common/arrow-se.svg
> +<path fill-rule="evenodd" clip-rule="evenodd" d="M9.52621 12.4915H11.6919C12.1545 12.4915 12.5295 12.8665 12.5295 13.3291C12.5295 13.7916 12.1545 14.1666 11.6919 14.1666L7.50421 14.1666C7.27293 14.16
```suggestion
<path fill-rule="evenodd" clip-rule="evenodd" d="M9.52621 12.4915H11.6919C12.1545 12.4915 12.5295 12.8665 12.5295 13.3291C12.5295 13.7916 12.1545 14.1666 11.6919 14.1666L7.50421 14.1666C7.27293 14.1666 7.06354 14.0729 6.91198 13.9213C6.76041 13.7698 6.66667 13.5604 6.66667 13.3291V9.14137C6.66667 8.67881 7.04165 8.30383 7.50421 8.30383C7.96677 8.30383 8.34175 8.67881 8.34175 9.14137V11.3071L13.5702 6.0786C13.8973 5.75152 14.4276 5.75152 14.7547 6.0786C15.0818 6.40568 15.0818 6.93599 14.7547 7.26307L9.52621 12.4915Z" fill="currentColor"/>
```

2023-11-09 13:47 UTC, schmanu commented on public/images/common/arrow-top-right.svg
> +<path fill-rule="evenodd" clip-rule="evenodd" d="M12.2355 6.84341H9.63669C9.08161 6.84341 8.63164 6.39344 8.63164 5.83836C8.63164 5.28329 9.08161 4.83331 9.63669 4.83331H14.6619C14.9395 4.83331 15.19
```suggestion
<path fill-rule="evenodd" clip-rule="evenodd" d="M12.2355 6.84341H9.63669C9.08161 6.84341 8.63164 6.39344 8.63164 5.83836C8.63164 5.28329 9.08161 4.83331 9.63669 4.83331H14.6619C14.9395 4.83331 15.1907 4.94581 15.3726 5.12769C15.5545 5.30956 15.667 5.56083 15.667 5.83836V10.8636C15.667 11.4187 15.217 11.8687 14.6619 11.8687C14.1069 11.8687 13.6569 11.4187 13.6569 10.8636V8.26477L7.38272 14.5389C6.99022 14.9314 6.35386 14.9314 5.96136 14.5389C5.56887 14.1464 5.56887 13.5101 5.96136 13.1176L12.2355 6.84341Z" fill="currentColor"/>
```

2023-11-09 14:09 UTC, schmanu approved these changes
The app is also listed now on staging and the button works :)

2023-11-09 15:25 UTC, katspaugh commented
The skeletons need some adjustments, it jumps twice when loading.

https://github.com/safe-global/safe-wallet-web/assets/381895/1d2d3242-14a1-498e-908f-89de91d03eec

2023-11-10 01:10 UTC, francovenica commented
For mobile if the "Buy" button is present is all too cramped:
![image](https://github.com/safe-global/safe-wallet-web/assets/4503659/e49c12c8-2374-49db-8762-ad06cc0ae73d)

Question just out of curiosity: why the "Buy" is an "a" tag, the "Send" is a button and the "Receive" is a button wrapped in a div?

2023-11-10 09:59 UTC, usame-algan commented
I updated the loading state and mobile view accordingly

> Question just out of curiosity: why the "Buy" is an "a" tag, the "Send" is a button and the "Receive" is a button wrapped in a div?

The Buy Crypto button is an `a` because it links to a different page. The Receive button is wrapped in a `div` because we are reusing a wrapper component that adds an onClick handler around its children so there has to be some element to hold that.

2023-11-10 10:32 UTC, katspaugh commented
Can you make Send and Receive be on the same line, and Buy crypto on a different line?

2023-11-10 10:41 UTC, usame-algan commented
Changed it like so on mobile:
<img width="414" alt="Screenshot 2023-11-10 at 11 40 57" src="https://github.com/safe-global/safe-wallet-web/assets/5880855/1571ff57-c3d3-4927-8797-0b9d19354edc">

2023-11-10 11:34 UTC, merged