Tests: e2e - select connected wallet (patch)
safe-global/safe-wallet-web pull request #2911
Opened 2023-11-29 03:34 UTC by francovenica

## What it solves

There is an issue with the Create-tx test. Now that in Sepolia the Relayer is enabled you need to select the connected wallet option in the test. 
This is just a quick patch while I finish with the full refactor of the e2e-test, so the test doesn't fail in other PR's

## Checklist
* [ ] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

2023-11-29 13:19 UTC, katspaugh approved these changes

2023-11-29 13:19 UTC, katspaugh requested changes
You should follow POM like the other calls in that test.

2023-11-29 14:49 UTC, mike10ca requested changes
@francovenica 

1. Please add data-testid to 'Connected wallet' and use it in the test
2. Please create a method in support pages file to adhere to POM

2023-12-04 11:53 UTC, francovenica commented
@katspaugh @mike10ca Sorry, I messed up in the stand up. This patch was a quick fix so the PR's would stop failing because of the relayer in Sepolia.
Now that the [main ticket](https://github.com/safe-global/safe-wallet-web/pull/2948) I was working on is done this ticket is not useful anymore. 

I'll close it

2023-12-04 11:53 UTC, closed without merging