Feat: tx queue redesign
safe-global/safe-wallet-web pull request #3104
Opened 2024-01-12 13:34 UTC by katspaugh

## What it solves

Tx Queue redesign as per [Firma](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?type=design&node-id=9450-37369&mode=design&t=uMuRlcdouL6EZu0h-0)

## How this PR fixes it

* I've replaced the "compact" icon buttons for Confirming and Executing with actual buttons
* Adjusted the style of grouped conflicting txs
* Reworked the grid system on small screens

Todo (in another PR):
* [ ] Tooltip for the Confirmations chip
* [ ] Dropdown in the Confirm button

## Screenshots

Desktop (> 1200px):
<img width="1238" alt="Screenshot 2024-01-12 at 14 29 02" src="https://github.com/safe-global/safe-wallet-web/assets/381895/b1f93284-89fe-4578-864a-1d79cce5181d">

Mobile:
<img width="612" alt="Screenshot 2024-01-12 at 14 29 43" src="https://github.com/safe-global/safe-wallet-web/assets/381895/1f0c669f-ee83-462f-8ae6-1a4736a3dbd8">

2024-01-15 11:38 UTC, katspaugh commented on .github/workflows/deploy-dev.yml
> +            https://${{ steps.extract_branch.outputs.branch }}--walletweb.review-wallet-web.5afe.dev/home?safe=eth:0xA77DE01e157f9f57C7c4A326eeE9C4874D0598b6
Added this so that we can open the app on an actual Safe instead of the Welcome page.

2024-01-15 13:44 UTC, jmealy requested changes
The new conflicting transaction grouping looks nice 👍

2024-01-15 14:08 UTC, katspaugh commented on src/components/common/TokenAmount/styles.module.css
> +  font-weight: bold;
True, removed!

2024-01-15 14:23 UTC, jmealy approved these changes

2024-01-15 14:49 UTC, katspaugh commented
@TanyaEfremova could you do a design review of this branch?

2024-01-15 18:44 UTC, katspaugh commented
Good catch, thanks Tanya!

2024-01-16 10:19 UTC, liliya-soroka commented
Board for stabilisation - https://www.notion.so/safe-global/600cb549341647329beaef79359f1fff?v=5f7562b4ba7048a78d17d816f35589f3

2024-01-16 14:32 UTC, liliya-soroka commented
Checked:
- settings txs 
- send ETH
-  send ERC20
- send NFT
- contract interaction - 1 /2/3 actions
- safe-apps tx
- recovery /recovery+cancel 
-  a few txs with the same nonce, including reject tx
-  1 of N confirmation/ 2 of N / fully signed 
-  signing, executing processes
-  with/without next
- N days ago, N minutes ago, date interval
-  bulk execution
- messages /history tabs

2024-01-17 10:48 UTC, liliya-soroka commented
Verified

2024-01-17 12:05 UTC, merged