Separate watchlist from owned safes
safe-global/safe-wallet-web pull request #3258
Opened 2024-02-14 16:34 UTC by jmealy

Separate the list of safes on the my accounts page into owned safes and watchlist safes

Owned Safes includes:
- Safes that are both owned and added
- Safes that are owned but not added

Watchlist includes:
- safes that are owned but not added

## How to test it
- go to `/welcome/accounts`
- see the lists separated as described.

## Screenshots
<img width="778" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/17801424/a9bfbb1a-9e29-42a0-afda-0e93723b630a">

## Checklist
* [ ] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

2024-02-14 16:56 UTC, katspaugh requested changes
There's a significant code duplication now. Both the main list and the Watchlist are essentially the same component. Please extract it into a a paginated list component.

2024-02-14 16:56 UTC, katspaugh commented on src/components/welcome/MyAccounts/index.tsx
> +const PAGE_SIZE = 5
```suggestion
const PAGE_SIZE = 5

```

2024-02-15 09:51 UTC, katspaugh commented on src/components/welcome/MyAccounts/PaginatedSafeList.tsx
> +  title: ReactElement
```suggestion
  title: ReactNode
```

Then you can just pass a string.

2024-02-15 10:16 UTC, usame-algan commented on src/components/welcome/MyAccounts/PaginatedSafeList.tsx
> +  const [maxShownSafes, setMaxSafes] = useState<number>(DEFAULT_SHOWN)
nit: for consistency I would name the setter `setMaxShownSafes`

2024-02-15 10:16 UTC, usame-algan commented on src/components/welcome/MyAccounts/useAllSafes.ts
> +        isWatchlist: !(ownedOnChain || []).includes(address),
nit: `isOnWatchlist` or `isWatchlisted` sounds a bit more accurate

2024-02-15 10:24 UTC, jmealy commented on src/components/welcome/MyAccounts/PaginatedSafeList.tsx
> +  safeCount?: number
yes, passing it as a prop so that when it's absent (on the watchlist) it doesn't show the count in brackets

2024-02-15 10:27 UTC, usame-algan commented on src/components/welcome/MyAccounts/useAllSafes.ts
> +        isWatchlist: !(ownedOnChain || []).includes(address),
Unless this refers to an list of addresses then it would make sense 😄

2024-02-15 11:07 UTC, katspaugh commented on src/components/welcome/MyAccounts/PaginatedSafeList.tsx
> +  safeCount?: number
I suggest we should it there as well.

2024-02-15 11:08 UTC, katspaugh commented on src/components/welcome/MyAccounts/useAllSafes.ts
> +        isOnWatchlist: !(ownedOnChain || []).includes(address),
IMO the old name was better. Less grammatical but shorter.

2024-02-15 12:43 UTC, katspaugh approved these changes
Cheers!

2024-02-15 16:07 UTC, merged