Fix: rearrange Settings tabs
safe-global/safe-wallet-web pull request #3751
Opened 2024-05-27 08:26 UTC by katspaugh

## What it solves

* Security & Login -> Security
* Moved spending limits to Setup
* Setup items are more compact now

![Screenshot 2024-05-27 at 10 13 42](https://github.com/safe-global/safe-wallet-web/assets/381895/9166518b-dd00-4915-a5db-73c53ec8967d)

![Screenshot 2024-05-27 at 09 56 10](https://github.com/safe-global/safe-wallet-web/assets/381895/55e58ae4-e9a4-4212-89dd-680bc995c7cf)

2024-05-27 08:41 UTC, schmanu requested changes
Looks good.

There is a lint error and a test is failing tho.

2024-05-27 11:09 UTC, usame-algan commented
Do we also need to adjust e2e tests for spending limits not that it was moved to a different page?

2024-05-28 09:55 UTC, schmanu approved these changes

2024-05-28 14:27 UTC, katspaugh commented
I agree regarding a separate tab for limits. There's a bigger project in the works to revamp the settings, so it will be addressed there.

2024-05-28 14:27 UTC, merged