feat: incremend safe version constants
safe-global/safe-wallet-web pull request #3996
Opened 2024-07-24 13:38 UTC by schmanu

## How this PR fixes it
Set `LATEST_SAFE_VERSION` to `1.4.1`

This change does not offer a migration transaction for 1.3.0 Safes yet. That will follow in a separate PR.

## How to test it
We need a full regression for this feature as it affects most aspects of the interface.
I so far tested:
- Safe creation for 1.4.1
- Counterfactual Safe creation for 1.4.1
- Counterfactual Safe activation for a previously created 1.3.0 Safe
- Recovery with 1.4.1 Safe
- Recovery with an old 1.3.0 Safe
- Multisends
- Twaps

## Checklist
* [x] I've tested the branch on mobile 📱
* [x] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

2024-07-24 13:39 UTC, schmanu commented on README.md
> -| Env variable                                           | Description
This diff was some autoformatting by my VS Code.. If we do not want this I have to revert and Save without formatting.

2024-07-25 09:11 UTC, katspaugh approved these changes
🚀

2024-08-02 04:25 UTC, francovenica commented
This ticket is in ready for QA in notion so I tested it

LGTM

Upgrade a safe 1.1.1 to 1.4.1 in ETH mainnet( I don't have one in sepolia)
Recovery in safes 1.3.0
Recovery in safes 1.4.1
CF safes 1.4.1
Deployment or activation of a CF safe just fine (once done the "L2" shows up next to the version
The upgrade of a CF safe 1.3.0 (I had to create a CF safe in dev, copy/paste the local storage to have it in this PR)
Several tx of different kind:
Swap, limit and twaps
Send funds
signing messages
spending limits
owner editting

2024-08-02 05:27 UTC, katspaugh commented
Please don’t merge it yet, I’d like to make another release before this. Is it possible to hide it behind a feature toggle?

2024-08-02 08:58 UTC, liliya-soroka commented
Safe creation on ZKSync Era doesn't work 
![Uploading image.png…]()

2024-08-05 07:44 UTC, katspaugh commented on src/config/chains.ts
> +    '1.3.0') as SafeVersion
Let's extract `1.3.0` into a `FALLBACK_VERSION` constant.

Also, this file stopped being a "config" when we switched to generated chain lists. So I would suggest to not make it even less of a config and move this function to utils or services.

2024-08-07 09:40 UTC, katspaugh requested changes
Please add a feature toggle so that we can merge this PR any time and toggle a version switch remotely.

2024-08-09 10:39 UTC, katspaugh approved these changes
LGTM but e2e tests are failing

2024-08-12 02:19 UTC, francovenica commented
I tried to create a safe in those networks and they don't show the error now. I don't have funds for all those networks, but I was able to create it in zkSycn era and linea with no issues. Safes 1.3.0 were created for those

I tested every network again and none of them showed the error message. so LGTM

2024-08-12 11:20 UTC, katspaugh approved these changes
👍

2024-08-13 05:39 UTC, francovenica commented
I've been told by Andrei that the contracts for 1.4.1 safes have been deployed for all networks already. Should then be possible for these few networks where safes are still being created as 1.3.0 to now be created as 1.4.1?

2024-08-13 08:15 UTC, schmanu commented
@francovenica you got to enable the feature flag.
I will enable it on all chains except Polygon on staging such that you can also test that Polygon still uses 1.3.0.

2024-08-13 14:08 UTC, merged